template = "https://github.com/giellalt/template-lang-und"
rev_id = 256
template_sha = "4e2ddf168a2aaf68d2c29db9e79e44e1dc4c2b76"

[replacements]
__GLOTTOLOG_ID__ = "stan1295"
__REPO__ = "lang-deu"
__UND2C__ = "de"
__UNDEFINED__ = "German"
__UND__ = "deu"
