template = "https://github.com/giellalt/template-lang-und"
rev_id = 280
template_sha = "6beee360d8349c39749ac477719ead241493924c"

[replacements]
__GLOTTOLOG_ID__ = "stan1295"
__REPO__ = "lang-deu"
__UND2C__ = "de"
__UNDEFINED__ = "German"
__UND__ = "deu"
